---
# tasks file for ansible-role-minikube

- include_tasks: setup-linux.yml
  when: ansible_os_family == 'RedHat' or ansible_os_family == 'Debian'
  tags:
    - setup

- debug:
    msg: "This ansible role only supports RedHat or Debian or Ubuntu"
  when: ansible_os_family != 'RedHat' and ansible_os_family != 'Debian'
  tags:
    - setup

- include_tasks: startup-linux.yml
  when: ansible_os_family == 'RedHat' or ansible_os_family == 'Debian'
  tags:
    - startup
